# 데이터 사이언스 Toolkit

### 수업 목표
- 데이터 과학의 핵심 라이브러리 생태계(Numpy, Pandas, Matplotlib)를 **큰 그림**에서 이해한다.
- Numpy로 수치 데이터를 **효율적으로** 생성, 조작, 연산할 수 있다.
- 선형대수학의 기초 개념(벡터, 행렬, 연산, 전치/역행렬)을 **넘파이 코드로 구현**할 수 있다.

### 왜 Numpy, Pandas, Matplotlib 인가
- Numpy: 파이썬에서 **고성능 수치 연산**을 담당하는 **배열 엔진**. ML/DL의 전처리와 수치 연산의 기반.
- Pandas: **표 형식 데이터프레임**으로 정리·가공·집계에 최적. 실무 데이터 핸들링의 표준.
- Matplotlib: 분석 결과를 **시각화**하여 패턴을 발견하고 의사결정을 돕는다.

![image.png](image/numpy.png)
### Numpy의 특징

- **빠른 배열 연산**  
  - 파이썬의 기본 리스트보다 훨씬 빠른 속도로 벡터와 행렬 연산을 수행한다.  
  - 내부적으로 C 언어로 구현되어 있어 반복문을 직접 작성하지 않아도 된다.  

- **다양한 수학 함수 제공**  
  - 합계, 평균, 표준편차 같은 기본 통계부터, 선형대수(행렬 곱, 역행렬 등), 푸리에 변환까지 지원한다.  

- **브로드캐스팅(Broadcasting)**  
  - 크기가 다른 배열끼리도 규칙에 따라 자동으로 맞춰 연산할 수 있다.  
  - 예: 행렬 전체에 상수 더하기, 벡터를 행렬 각 행에 더하기. 
  
  - ![image-2.png](image/Broadcasting.png)  
  출처 : http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html


- **머신러닝/딥러닝의 기반**  
  - 텐서플로우(TensorFlow), 파이토치(PyTorch) 같은 딥러닝 프레임워크도 내부 연산을 Numpy와 유사한 구조로 수행한다.  
  - 즉, **Numpy 배열을 자유자재로 다룰 수 있어야 ML/DL의 연산 원리를 이해할 수 있다.**

## 0. 선형대수학 기초

### 0.1 벡터(Vector)
- 벡터는 여러 숫자를 **순서대로 나열한 것**  
- 흔히 화살표(방향과 크기) 또는 좌표처럼 생각할 수 있다.  
- 벡터는 "차원(dimension)"의 개수에 따라 구분된다.  


#### 1차원 벡터 (1D Vector)
- 숫자 1개만 가지는 벡터
- 단순히 **실수축 위의 한 점**  
- $\vec{v} = \begin{bmatrix} 3 \end{bmatrix}$ 
- ---●--------→ x


#### 2차원 벡터 (2D Vector)
- 숫자 2개 (x, y)  
- 평면 위의 점 혹은 "화살표"  
- $\vec{v} = \begin{bmatrix} 2 \\ 3 \end{bmatrix}$
```yaml
y ↑
|
3 | ● (2,3)
|
|—2—————→ x
```

#### 3차원 벡터 (3D Vector)
- 숫자 3개 (x, y, z)  
- 공간(입체) 속의 한 점  
- $\vec{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$
- 
- 좌표 (1,2,3) 은 "x축으로 1, y축으로 2, z축으로 3 이동한 점"을 의미한다.  

####  벡터의 연산
- 덧셈: 
$$
\begin{bmatrix} 1 \\ 2 \end{bmatrix} +
\begin{bmatrix} 3 \\ 4 \end{bmatrix} =
\begin{bmatrix} 4 \\ 6 \end{bmatrix}
$$

- 스칼라 곱: 
$$
2 \times \begin{bmatrix} 1 \\ 2 \end{bmatrix} =
\begin{bmatrix} 2 \\ 4 \end{bmatrix}
$$


### 0.2 행렬(Matrix)

- 행렬은 숫자를 **직사각형 모양**으로 배열한 것  
- 여러 벡터를 모아 만든 "데이터 표"  

예:  
$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
$$

- 크기: 3행 2열 (3×2 행렬)
#### 💡 행렬의 의미
- **데이터 표**: 행 = 샘플, 열 = 변수  
- **벡터의 집합**: 여러 벡터(2개 이상)의 모음
- **선형 변환**: 벡터를 입력하면, 특정 규칙(행렬 곱)에 따라 새로운 벡터로 바꿔주는 과정
→ 마치 벡터를 "회전, 확대/축소, 반사"시키는 것처럼 생각할 수 있다.


### 0.3 행렬 연산

1. **덧셈/뺄셈**  
   - 같은 크기의 행렬끼리만 가능  
   $$
   \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} +
   \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} =
   \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}
   $$

2. **스칼라 곱**  
   - 모든 원소에 같은 수 곱하기  
   $$
   2 \times \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} =
   \begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}
   $$

3. **행렬 곱**  
   - "앞 행렬의 행 × 뒤 행렬의 열"  
   - (m×n) × (n×p) = (m×p)  
   $$
   \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
   \times
   \begin{bmatrix} 5 \\ 6 \end{bmatrix}
   =
   \begin{bmatrix} 17 \\ 39 \end{bmatrix}
   $$


### 0.4 전치/단위/역행렬

- **전치행렬 (Transpose)**: 행과 열을 뒤바꾼 행렬  
  $$
  \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}^T =
  \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}
  $$

- **단위행렬 (Identity)**: 대각선이 1, 나머지는 0  
  $$
  I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
  $$

- **역행렬 (Inverse)**: A와 곱했을 때 단위행렬이 되는 행렬  
  $$
  A \times A^{-1} = I
  $$

### 0.5 선형시스템 (Ax = b)

- 연립방정식을 행렬과 벡터로 표현할 수 있다.

예:  
$$
2x + y = 4 \\
x - y = 1
$$

- → 행렬 표현: 

    $$
    \begin{bmatrix}
    2 & 1 \\
    1 & -1
    \end{bmatrix}
    \begin{bmatrix}
    x \\
    y
    \end{bmatrix}
    =
    \begin{bmatrix}
    4 \\
    1
    \end{bmatrix}
    $$

👉 연립방정식을 간단히 \(Ax = b\) 꼴로 표현할 수 있다.



### 체크포인트
- **벡터**는 숫자의 나열이며, 1D/2D/3D로 구분된다.  
- **행렬**은 여러 벡터를 모아둔 2차원 구조다.  
- 행렬 곱은 "행 × 열" 규칙으로 계산한다.  
- 전치, 단위, 역행렬은 행렬의 기본 개념이다.  
- 연립방정식은 \(Ax = b\) 로 표현할 수 있다.


## 1. Numpy 기초

#### 배열이란?
- **배열(array)** 은 같은 종류의 데이터를 일정한 모양(행렬 형태)으로 모아놓은 것
- 파이썬 기본 리스트(list)와 달리, 배열은 **모든 원소가 같은 자료형**을 가지며 **고속 연산**이 가능
- 데이터 과학에서 다루는 데이터(표, 이미지, 시계열)는 대부분 "숫자들의 모음" → 배열로 표현하면 효율적

예시:
- 1차원 배열: `[1, 2, 3, 4]` (벡터)
- 2차원 배열: `[[1, 2], [3, 4]]` (행렬)
- 3차원 배열: 이미지(높이 × 너비 × 색상 채널)

#### 배열 생성 방법

- `np.array(리스트)` : 파이썬 리스트를 배열로 변환
- `np.arange(시작, 끝, 간격)` : 특정 범위의 정수를 순차적으로 생성
- `np.zeros(크기)` : 0으로 채운 배열 생성
- `np.ones(크기)` : 1로 채운 배열 생성
- `np.linspace(시작, 끝, 개수)` : 지정한 구간을 일정 간격으로 나눈 값 생성

#### 자료형 (dtype)

- 배열의 모든 원소는 **같은 자료형(dtype)** 을 가짐
- 기본적으로는 입력 데이터에 따라 자동 결정되지만, 직접 지정 가능
- 주요 자료형: int32, float64, bool, str
- `dtype` 로 자료형 지정 및 확인 가능

👉 여기서 `int32`의 **32**는 "32비트 정수"라는 뜻  
- **비트(bit)** = 컴퓨터가 정보를 저장하는 최소 단위 (0 또는 1)  
- **32비트 정수**는 32개의 0/1로 수를 표현 → 약 ±21억까지 표현 가능  
- **64비트 정수**는 더 많은 비트를 쓰기 때문에 훨씬 더 큰 수까지 표현 가능  
- 마찬가지로 `float32`, `float64`는 소수점 실수를 32비트 / 64비트로 저장  
  → 64비트는 더 정밀한 소수 계산 가능  

즉, 숫자가 커지거나 정밀도가 필요할수록 더 많은 비트를 사용하는 자료형을 선택한다.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])                 # 기본 배열
b = np.arange(0, 10, 2)                 # 0,2,4,6,8
z = np.zeros((2, 3), dtype=np.float32)  # 2x3 영행렬
o = np.ones((3, 1))                     # 3x1 일행렬
l = np.linspace(0, 1, 5)                # 0~1 구간 5등분

print(a.dtype, z.shape, l)

## 2. 인덱싱(Indexing)과 슬라이싱(Slicing)

#### 배열에서 값 꺼내기 (Indexing)
- 배열의 특정 위치에 접근할 때는 **인덱스(index)** 사용
- 파이썬과 Numpy는 **0부터 시작**
- 음수 인덱스는 뒤에서부터 세기

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # 첫 번째 원소 → 10
print(arr[-1])  # 마지막 원소 → 50

#### 배열의 일부 꺼내기 (Slicing)

- 시작:끝 형태로 잘라내기 (끝은 포함되지 않음)
- 시작:끝:간격 으로 일정 간격으로 추출 가능

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[2:5])    # 인덱스 2~4 → [2 3 4]
print(arr[:4])     # 처음~3까지 → [0 1 2 3]
print(arr[5:])     # 5부터 끝까지 → [5 6 7 8 9]
print(arr[::2])    # 2칸씩 건너뛰기 → [0 2 4 6 8]

#### 2차원 배열에서 인덱싱/슬라이싱
- [행, 열] 형태로 접근
- 슬라이싱은 각각의 차원에 적용 가능

In [ ]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat[0, 0])     # (0행, 0열) → 1
print(mat[1, :])     # 1행 전체 → [4 5 6]
print(mat[:, 2])     # 모든 행의 2열 → [3 6 9]
print(mat[0:2, 1:3]) # 부분 배열(0~1행, 1~2열)

### 연습 문제

### 문제 1
1부터 10까지의 정수를 원소로 가지는 배열을 만들고,  
- 첫 번째 원소  
- 마지막 원소  
- 인덱스 3~6 구간 (즉, 4번째부터 7번째까지)  

를 각각 출력하세요.



In [ ]:
# 여기에 문제 1 작성하세요


### 문제 2
다음 배열이 있을 때  
```python
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
```
- 2행 전체를 출력하세요.
- 1열(세로 방향)을 출력하세요.
- 부분 배열 [[20, 30], [50, 60]] 을 슬라이싱으로 꺼내보세요.

In [ ]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])


## 3. 불린 인덱싱
**불린 인덱싱이란?**
- 배열에서 **조건을 만족하는 원소만** 골라내는 방법
- 조건식을 쓰면 True/False 로 된 "마스크(mask)" 배열이 만들어지고,
  이 마스크를 원래 배열에 적용하면 True인 원소만 선택됨

In [ ]:
y = np.array([3, 6, 9, 12, 15])
mask = (y % 6 == 0)
print(mask)     # [False  True False  True False]
print(y[mask])  # [ 6 12] 

#### 여러 조건 결합
- `&` (and), `|` (or), `~` (not) 를 이용해 조건을 결합할 수 있음


In [ ]:
arr = np.array([10, 15, 20, 25, 30])

# 15 이상이고 30 미만인 원소만
print(arr[(arr >= 15) & (arr < 30)])   # [15 20 25]

In [ ]:
# 20이 아닌 원소만
print(arr[arr != 20]) # [10 15 25 30]

### 불린 인덱싱의 장점
- 반복문 없이 조건에 맞는 데이터를 빠르게 추출 가능
- 데이터 분석에서 "필터링"할 때 매우 유용

#### ✅ 체크포인트
- 불린 인덱싱은 **조건식 → True/False 배열 → True만 선택** 과정이다.
- 조건을 결합할 때는 `and/or` 대신 `&` 와 `|` 를 쓴다.
- `~` 는 조건을 반대로 뒤집는다.


### 연습 문제

### 문제 1
아래 배열이 있을 때,
- 15보다 큰 원소만 출력하세요.
- 10 이상 25 이하인 원소만 출력하세요.
```python
arr = np.array([5, 10, 15, 20, 25, 30])
```

In [ ]:
# 여기에 문제 1 작성하세요
arr = np.array([5, 10, 15, 20, 25, 30])


### 문제 2
다음 배열이 있을 때,
- 3의 배수이면서 2의 배수인 원소만 출력하세요.
- 10보다 작거나 15보다 큰 원소만 출력하세요.

```python
arr = np.array([3, 6, 9, 12, 15, 18])
```

In [ ]:
# 여기에 문제 2 작성하세요
arr = np.array([3, 6, 9, 12, 15, 18])


## 4. 기본 연산 (Arithmetic & Aggregation)

### 1) 스칼라 연산
- 배열과 숫자(스칼라)를 더하거나 빼면, 모든 원소에 연산이 적용됨
- 반복문을 쓰지 않아도 자동으로 전체 원소에 반영됨

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)   # [11 12 13 14 15]
print(arr * 2)    # [ 2  4  6  8 10]

### 2) 배열 간 연산
- 같은 크기의 배열끼리는 원소별로 연산이 수행됨
- (행렬 곱이 아니라, 원소별 곱이라는 점에 주의!)


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)   # [11 22 33]
print(a * b)   # [10 40 90]
print(a ** 2)  # [1 4 9]

### 3) 집계 함수 (Aggregation)
- 배열 전체의 합계, 평균, 최댓값 등을 한 번에 계산
- 자주 쓰이는 함수: `sum`, `mean`, `max`, `min`, `argmax`, `argmin`

In [ ]:
import numpy as np

x = np.array([5, 7, 3, 9])

print(x.sum())      # 24 (합계)
print(x.mean())     # 6.0 (평균)
print(x.max())      # 9 (최댓값)
print(x.min())      # 3 (최솟값)
print(x.argmax())   # 3 (최댓값의 위치)
print(x.argmin())   # 2 (최솟값의 위치)

### 4) 다차원 배열에서의 집계
- `axis` 옵션을 이용하면 행/열 방향으로 집계를 낼 수 있음
- `axis=0`: 세로 방향(열 단위)
- `axis=1`: 가로 방향(행 단위)

In [ ]:
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

print(mat.sum())         # 21 (전체 합)
print(mat.sum(axis=0))   # [5 7 9] (열별 합)
print(mat.sum(axis=1))   # [6 15]  (행별 합)


### ✅ 체크포인트
- 스칼라 연산: 배열의 모든 원소에 동일하게 적용된다.
- 배열 간 연산: 같은 위치끼리 원소별 연산을 수행한다.
- 집계 함수: 전체/행/열 단위로 합계, 평균, 최댓값 등을 계산할 수 있다.


### 연습 문제

### 문제 1
배열 arr = np.array([2, 4, 6, 8, 10])에 대해:

1. 모든 원소를 제곱한 결과를 출력하세요.
2. 모든 원소의 평균을 출력하세요.

<details>
<summary>정답</summary>

```python
import numpy as np

arr = np.array([2, 4, 6, 8, 10])
print(arr ** 2)     # [  4  16  36  64 100]
print(arr.mean())   # 6.0

</details>

In [ ]:
# 여기에 작성하세요
import numpy as np
arr = np.array([2, 4, 6, 8, 10])

### 문제 2

아래 2차원 배열에 대해 
- 전체 합계를 구하세요.
- 각 열의 최댓값을 구하세요.
- 각 행의 평균을 구하세요.
```python 
mat = np.array([[10, 20, 30],
                [40, 50, 60]])
```

<details>
<summary>정답</summary>

```python
import numpy as np

mat = np.array([[10, 20, 30],
                [40, 50, 60]])

print(mat.sum())        # 210
print(mat.max(axis=0))  # [40 50 60]
print(mat.mean(axis=1)) # [20. 50.]
```

</details>

In [ ]:
# 여기에 작성하세요
import numpy as np

## 5. Numpy 심화

### 1) 배열 결합 (Concatenate, Stack)

#### 배열 합치기 (concatenate)
- 여러 배열을 하나로 이어 붙이는 기능
- `axis=0`: 행(세로)로 붙이기  
- `axis=1`: 열(가로)로 붙이기

In [ ]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6]])

print(np.concatenate([a, b], axis=0))
# [[1 2]
#  [3 4]
#  [5 6]]

#### 배열 쌓기 (stack)
- 차원을 하나 늘려서 쌓음
- np.stack([a, b], axis=0) → 새로운 축 생성

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(np.stack([x, y], axis=0))
# [[1 2 3]
#  [4 5 6]]

### 2) 3.2 브로드캐스팅 (Broadcasting)
- 크기가 다른 배열끼리 연산할 때, 작은 배열을 자동으로 확장해 맞추는 기능
- 규칙: 뒤에서부터 차원을 비교 → 1 또는 같은 크기면 연산 가능

  <img src="image/Broadcasting.png">


In [ ]:
np.ones((3, 4))

In [ ]:
M = np.ones((3, 4))   # (3행 4열)
row = np.array([1, 2, 3, 4])   # (4,)

print(M + row)
# 각 행에 row가 더해짐

In [ ]:
col = np.array([[10],
                [20],
                [30]])  # (3행 1열)

print(M + col)
# 각 열에 col이 더해짐

### 연습 문제

### 문제 1
아래 두 배열을 이어 붙여 새로운 배열을 만들어보세요.

```python
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6]])
```

- axis=0 방향으로 합치기
- axis=1 방향으로 합치기

<details>
<summary>정답</summary>

```python
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6]])

print(np.concatenate([a, b], axis=0))
# [[1 2]
#  [3 4]
#  [5 6]]

print(np.concatenate([a, b.T], axis=1))
# [[1 2 5]
#  [3 4 6]]
```
</details>

### 체크포인트
- `concatenate`: 배열을 이어붙인다. (axis=0: 세로, axis=1: 가로)

- `stack`: 새로운 차원을 추가해서 배열을 쌓는다.

- **브로드캐스팅**: 크기가 맞지 않는 배열도 규칙에 따라 자동 확장하여 연산 가능하다.

In [ ]:
### 여기에 작성하세요
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6]])

### 문제 2

다음 배열이 있을 때, 브로드캐스팅을 이용해 계산하세요.

```python
M = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([10, 20, 30])
```

M + v 의 결과를 출력하세요.

<details> <summary>정답</summary>

```python
import numpy as np

M = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([10, 20, 30])

print(M + v)
# [[11 22 33]
#  [14 25 36]]
```
</details>

In [ ]:
### 여기에 작성하세요
M = np.array([[1, 2, 3],
              [4, 5, 6]])
v = np.array([10, 20, 30])

### 문제 3

길이 3 벡터 x = [1, 2, 3], y = [4, 5, 6]를

- stack을 이용해 (2행 3열) 배열로 만들기
- stack을 이용해 (3행 2열) 배열로 만들기

<details><summary>정답</summary>

```python
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(np.stack([x, y], axis=0))
# [[1 2 3]
#  [4 5 6]]

print(np.stack([x, y], axis=1))
# [[1 4]
#  [2 5]
#  [3 6]]
```
</details> 

In [ ]:
### 여기에 작성하세요
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

### 문제 4
아래 배열에서 짝수만 골라내는 코드를 작성하세요.

```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
```

<details><summary>정답</summary>

```python
print(arr[arr % 2 == 0])
# [ 2  4  6  8 10]
```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

### 문제 5
아래 배열의 평균, 표준편차, 분산을 구하세요.

```python
arr = np.array([1, 2, 3, 4, 5])
```

<details><summary>정답</summary>

```python
print(np.mean(arr))  # 3.0
print(np.std(arr))   # 1.4142135623730951
print(np.var(arr))   # 2.0
```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([1, 2, 3, 4, 5])

### 문제 6
0부터 19까지의 정수로 이루어진 1차원 배열을 만들고, 이를 (4, 5) 모양으로 재구성하세요.

<details><summary>정답</summary>

```python
arr = np.arange(20)
print(arr.reshape(4, 5))
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]
#  [15 16 17 18 19]]
```
</details>

In [ ]:
### 여기에 작성하세요

### 문제 7
아래 배열의 각 행의 합과 각 열의 합을 구하세요.

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
```

<details><summary>정답</summary>

```python
print(np.sum(arr, axis=1))  # [ 6 15 24]
print(np.sum(arr, axis=0))  # [12 15 18]
```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

### 문제 8
아래 배열에서 최댓값과 최솟값, 그리고 각각의 위치(인덱스)를 구하세요.

```python
arr = np.array([10, 50, 30, 70, 20])
```

<details><summary>정답</summary>

```python
print(np.max(arr))        # 70
print(np.min(arr))        # 10
print(np.argmax(arr))     # 3
print(np.argmin(arr))     # 0
```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([10, 50, 30, 70, 20])

### 문제 9
아래 배열을 1차원으로 평탄화하세요.

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
```

<details><summary>정답</summary>

```python
print(arr.flatten())
# [1 2 3 4 5 6]
```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

### 문제 10
0과 1 사이의 난수를 원소로 가지는 (3, 3) 배열을 만드세요.

<details><summary>정답</summary>

```python
arr = np.random.rand(3, 3)
print(arr)
```
</details>

In [ ]:
# 여기에 작성하세요


### 문제 11
아래 배열을 전치(transpose)하세요.

```python
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
```

<details><summary>정답</summary>

```python
print(arr.T)
# [[1 3 5]
#  [2 4 6]]
```
</details>

In [ ]:
### 여기에 작성하세요

### 문제 12
아래 배열에서 5보다 큰 값만 0으로 바꾸세요.

```python
arr = np.array([1, 6, 3, 8, 5, 10])
```

<details><summary>정답</summary>

```python
arr[arr > 5] = 0
print(arr)
# [1 0 3 0 5 0]
```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([1, 6, 3, 8, 5, 10])

### 문제 13
아래 배열에서 두 번째 행과 세 번째 열만 추출하세요.

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
```

<details><summary>정답</summary>

```python
print(arr[1, :])   # [4 5 6]
print(arr[:, 2])   # [3 6 9]
```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

### 문제 14
아래 배열을 이용하여 행렬 곱셈을 수행하세요.

```python
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
```

<details><summary>정답</summary>

```python
print(np.matmul(a, b))
# [[19 22]
#  [43 50]]
```
</details>

In [ ]:
### 여기에 작성하세요
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

#### 난수 시드 설정

**난수 시드 설정이란?**

- NumPy에서 난수(랜덤 숫자)를 생성할 때, 결과의 재현 가능성을 보장하기 위해 사용하는 초기값 설정 방법
- 난수 생성은 기본적으로 예측 불가능하지만, 시드를 설정하면 동일한 난수 시퀀스를 반복적으로 얻을 수 있음
- 주로 실험 재현, 디버깅, 테스트 등에서 사용됨

`예시`

```python
시드 설정 없이 난수 생성
pythonimport numpy as np
print(np.random.rand(3))  # 매번 다른 난수 출력, 예: [0.123, 0.456, 0.789]
print(np.random.rand(3))  # 또 다른 난수 출력, 예: [0.321, 0.654, 0.987]

시드 설정 후 난수 생성
pythonimport numpy as np
np.random.seed(42)  # 시드값 42 설정
print(np.random.rand(3))  # 출력: [0.37454012, 0.95071431, 0.73199394]
np.random.seed(42)  # 동일한 시드값 재설정
print(np.random.rand(3))  # 출력: [0.37454012, 0.95071431, 0.73199394] (동일)
```

### 문제 15
난수 시드를 42로 고정한 뒤, (2, 5) 크기의 정수 배열을 0~9 범위에서 무작위로 생성하세요.

<details><summary>정답</summary>

```python
np.random.seed(42)
arr = np.random.randint(0, 10, (2, 5))
print(arr)
```
</details>

In [ ]:
### 여기에 작성하세요

### 문제 16
아래 배열의 각 원소에 제곱을 취한 배열을 만드세요.

```python
arr = np.array([1, 2, 3, 4, 5])
```

<details><summary>정답</summary>

```python
print(np.square(arr))
# [ 1  4  9 16 25]
```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([1, 2, 3, 4, 5])

### 문제 17
아래 배열에서 유일한 값(중복 제거된 값)들을 오름차순으로 출력하세요.

```python
arr = np.array([1, 2, 3, 2, 4, 1, 5, 3])
```

<details><summary>정답</summary>

```python
print(np.unique(arr))
# [1 2 3 4 5]
```
</details>

In [ ]:
### 여기에 작성하세요

### 문제 18
아래 배열을 정규화(평균=0, 표준편차=1)하세요.

```python
arr = np.array([1, 2, 3, 4, 5])
```
정규화 공식 (x - mean(x)) / std(x)
<details><summary>정답</summary>

```python
normalized = (arr - np.mean(arr)) / np.std(arr)
print(normalized)
# [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([1, 2, 3, 4, 5])


### 문제 19
아래 배열을 슬라이싱해서 (2, 2) 크기의 부분 배열을 만드세요.

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
```

<details><summary>정답</summary>

```python
print(arr[0:2, 1:3])
# [[2 3]
#  [5 6]]
```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

### 문제 20
아래 배열에서 각 열의 최댓값을 구하세요.

```python
arr = np.array([[1, 7, 3],
                [4, 5, 9],
                [2, 8, 6]])
```

<details><summary>정답</summary>

```python
print(np.max(arr, axis=0))
# [4 8 9]
```
</details>

In [ ]:
### 여기에 작성하세요
arr = np.array([[1, 7, 3],
                [4, 5, 9],
                [2, 8, 6]])

### 문제 21
아래 배열에서 3의 배수는 `"Fizz"`, 5의 배수는 `"Buzz"`, 15의 배수는 `"FizzBuzz"`로 바꾸고 출력하세요.  

```python
arr = np.arange(1, 21)
```

<details><summary>정답</summary>

```python
arr_str = arr.astype("object")

arr_str[arr % 15 == 0] = "FizzBuzz"
arr_str[(arr % 3 == 0) & (arr % 15 != 0)] = "Fizz"
arr_str[(arr % 5 == 0) & (arr % 15 != 0)] = "Buzz"

print(arr_str)
# [1 2 'Fizz' 4 'Buzz' 'Fizz' 7 8 'Fizz' 'Buzz' 11 'Fizz' 13 14 'FizzBuzz'
#  16 17 'Fizz' 19 'Buzz']
```
</details>


In [ ]:
arr = np.arange(1, 21)

### 문제 22
0과 1 사이의 난수로 이루어진 (5, 5) 배열을 만들고,  
`0.3 ≤ 값 ≤ 0.7` 인 원소는 모두 0으로 바꾸세요.  

<details><summary>정답</summary>

```python
np.random.seed(42)
arr = np.random.rand(5, 5)
arr[(arr >= 0.3) & (arr <= 0.7)] = 0
print(arr)
```
</details>


In [ ]:
### 여기에 작성하세요


### 문제 23
1부터 100까지의 숫자로 이루어진 배열을 (10, 10) 모양으로 만들고,  
짝수는 그대로 두고 홀수는 모두 -1로 바꾸세요.  

<details><summary>정답</summary>

```python
arr = np.arange(1, 101).reshape(10, 10)
arr[arr % 2 == 1] = -1
print(arr)
```
</details>

In [ ]:
### 여기에 작성하세요


### 문제 24
1부터 1,000,000까지의 숫자를 제곱한 결과를 각각 파이썬 리스트와 넘파이 배열을 이용해 계산하고,
두 방법의 실행 시간을 각각 출력하여 비교하세요.

<details><summary>정답</summary>

```python
import time
import numpy as np

# 리스트 연산
start = time.time()
list_result = [x**2 for x in range(1, 1_000_001)]
end = time.time()
print("리스트 연산 시간:", end - start)

# 넘파이 연산
arr = np.arange(1, 1_000_001)
start = time.time()
np_result = arr ** 2
end = time.time()
print("넘파이 연산 시간:", end - start)
```
</details>


In [ ]:
### 여기에 작성하세요


### 심화문제

### 심화 1

아래 이미지를 넘파이 배열로 읽어서 (이미지 경로 : image/dog_gray.jpg)  
① 모든 원소 값을 절반으로 줄이고,  
② 배열의 가운데 20×20 영역만 밝기를 0으로 만들어라.  

이미지 출처 : https://pixabay.com/ko/photos/%ED%9D%91%EB%B0%B1-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EA%B2%80%EC%A0%95%EC%83%89%EA%B3%BC-%ED%9D%B0%EC%83%89-8598798/

<details><summary>정답</summary>

```python
import matplotlib.pyplot as plt
arr = plt.imread('image/dog_gray.jpg')
plt.imshow(arr, cmap='gray')

# ① 전체 밝기를 절반으로 줄이기
arr_half = arr // 2

# ② 가운데 50x50 영역만 0으로 만들기
h, w = arr_half.shape
center_h, center_w = h // 2, w // 2
arr_half[center_h-10:center_h+10, center_w-10:center_w+10] = 0

# 결과 출력
plt.imshow(arr_half, cmap='gray')
plt.axis("off")
plt.show()

```
</details>


In [ ]:
import matplotlib.pyplot as plt
arr = plt.imread('image/dog_gray.jpg')
plt.imshow(arr, cmap='gray')

### 심화 2
몬테카를로 방법으로 원주율 π를 근사하라.
단, 1,000,000개의 난수를 생성하고, [0,1]×[0,1] 정사각형 안에 난수를 뿌린 후,
원의 1/4 내부에 들어온 점들의 비율을 이용해 π를 추정하라.

<details><summary>정답</summary>

```python
import numpy as np

N = 1_000_000

# 난수 생성
x = np.random.rand(N)
y = np.random.rand(N)

# 원 내부 조건 (x^2 + y^2 <= 1)
inside = (x**2 + y**2) <= 1

# 비율 계산
pi_est = (inside.sum() / N) * 4

print("추정한 원주율:", pi_est)

```
</details>


In [ ]:
import numpy as np

N = 1_000_000

# 난수 생성
x = np.random.rand(N)
y = np.random.rand(N)

### 심화 3
1부터 1000까지의 숫자로 이루어진 곱셈표(1000×1000 행렬)를 생성하라.
단, 이중 for문을 쓰지 말고 넘파이의 브로드캐스팅을 활용하여 구현하라.

```
array([[      1,       2,       3, ...,     998,     999,    1000],
       [      2,       4,       6, ...,    1996,    1998,    2000],
       [      3,       6,       9, ...,    2994,    2997,    3000],
       ...,
       [    998,    1996,    2994, ...,  996004,  997002,  998000],
       [    999,    1998,    2997, ...,  997002,  998001,  999000],
       [   1000,    2000,    3000, ...,  998000,  999000, 1000000]])
```
<details><summary>정답</summary>

```python
import numpy as np

arr = np.arange(1, 1001)
table = arr[:, None] * arr[None, :]   # 브로드캐스팅

print(table)

```
</details>
